import TelegramBot from 'node-telegram-bot-api';
import { startHandler } from './handlers/start.js';
import { mainMenuHandler } from './handlers/menu.js';
import { schoolInfoHandler } from './handlers/schoolInfo.js';
import { studyFormatsHandler } from './handlers/studyFormats.js';
import { advantagesHandler } from './handlers/advantages.js';
import { faqHandler } from './handlers/faq.js';
import { reviewsHandler } from './handlers/reviews.js';
import { teachersHandler } from './handlers/teachers.js';
import { studyHandler } from './handlers/study.js';
import { testHandler } from './handlers/test.js';
import { contactManagerHandler } from './handlers/contactManager.js';
import { setBotCommands } from './setBotCommands.js';
import { sendPackageInfoHandler } from './handlers/sendPackageInfoHandler.js';

const token = '8093162300:AAERaFyiqaWZn_mkAwtyYtd9epPHNvSFX0s';
const bot = new TelegramBot(token, { polling: true });

setBotCommands(bot);
startHandler(bot);
mainMenuHandler(bot);
schoolInfoHandler(bot);
studyFormatsHandler(bot);
advantagesHandler(bot);
faqHandler(bot);
reviewsHandler(bot);
teachersHandler(bot);
studyHandler(bot);
testHandler(bot);
contactManagerHandler(bot);
sendPackageInfoHandler(bot);
